/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import conn.ConexionMySQL;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SALA-3
 */
public class Plataformas extends javax.swing.JFrame {

    /**
     * Creates new form Plataformas
     */
    ConexionMySQL cmsql = new ConexionMySQL();
    Connection cn = cmsql.conectBdd();
    boolean txtField = false;
    boolean txtArea = false;
    int id = 0;

    public Plataformas() {
        initComponents();
        mostrarDatos();
        
        mostrarDatoPlataforma();
    }
    
    public void mostrarDatoPlataforma() {
        boxPlataforma.removeAllItems();
        boxPlataforma.addItem("Selecciona plataforma: ");
        try {
            Statement stt = cn.createStatement();
            ResultSet rst = stt.executeQuery("Select * from plataformas");
            
            while (rst.next()) {
                boxPlataforma.addItem(rst.getString(2));
            }
        } catch (Exception ex) {
            System.out.println("Mensaje: " + ex.getMessage());
        }
    }
    
    public void mostrarDatos() {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("ID");
        dtm.addColumn("Plataforma");
        dtm.addColumn("Descripcion");
        
        DataTable.setModel(dtm);
        
        try {
            String [] data = new String[3];
            Statement set = cn.createStatement();
            ResultSet rst = set.executeQuery("SELECT * FROM plataformas");
            while(rst.next()) {
                data[0] = rst.getString(1);
                data[1] = rst.getString(2);
                data[2] = rst.getString(3);
                dtm.addRow(data);
            }
            DataTable.setModel(dtm);
        } catch (Exception ex) {
            System.out.println("Mensaje: \n" + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        plataform = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descript = new javax.swing.JTextArea();
        BtnOK = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        boxPlataforma = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        DataTable = new javax.swing.JTable();

        jMenu1.setText("Modificar");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenu1);

        jMenuItem1.setText("Eliminar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Insert"));

        jLabel1.setText("Plataforma: ");

        jLabel2.setText("Descripteishon: ");

        plataform.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                plataformFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                plataformFocusLost(evt);
            }
        });
        plataform.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                plataformKeyReleased(evt);
            }
        });

        descript.setColumns(20);
        descript.setRows(5);
        descript.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                descriptFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                descriptFocusLost(evt);
            }
        });
        descript.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                descriptKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(descript);

        BtnOK.setText("OK");
        BtnOK.setEnabled(false);
        BtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOKActionPerformed(evt);
            }
        });

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        boxPlataforma.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxPlataforma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxPlataformaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(plataform, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnOK)
                            .addComponent(boxPlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(plataform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnOK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(30, 30, 30)
                        .addComponent(boxPlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        DataTable.setComponentPopupMenu(jPopupMenu1);
        jScrollPane2.setViewportView(DataTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOKActionPerformed

        if (!plataform.getText().equals("") && !descript.getText().equals("")) {
            try {
                PreparedStatement sent = cn.prepareStatement("INSERT INTO plataformas (nombre, descripcion) VALUES (?, ?)");
                sent.setString(1, plataform.getText());
                sent.setString(2, descript.getText());
                sent.executeUpdate();
                mostrarDatos();
            } catch (Exception ex) {
                System.out.println("Sorry \n" + ex.getMessage());
            }

            plataform.setText("");
            descript.setText("");
            System.out.println("Exito!! :P");
            JOptionPane.showMessageDialog(null, "Exito!! :)");
        } else {
            System.out.println("Sorry my friend :(");
            JOptionPane.showMessageDialog(null, "Sorry my friend!! :'(");
        }
        
        BtnOK.setEnabled(false);
    }//GEN-LAST:event_BtnOKActionPerformed

    private void plataformFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_plataformFocusLost
        
    }//GEN-LAST:event_plataformFocusLost

    private void descriptFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descriptFocusLost
        
    }//GEN-LAST:event_descriptFocusLost

    private void plataformFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_plataformFocusGained
        //BtnOK.setEnabled(false);
    }//GEN-LAST:event_plataformFocusGained

    private void descriptFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descriptFocusGained
        //BtnOK.setEnabled(false);
    }//GEN-LAST:event_descriptFocusGained

    private void plataformKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_plataformKeyReleased
        if (!plataform.getText().equals("")) {
            txtField = true;
        } else {
            txtField = false;
        }
        if (txtField == true && txtArea == true) {
            BtnOK.setEnabled(true);
        } else {
            BtnOK.setEnabled(false);
        }
    }//GEN-LAST:event_plataformKeyReleased

    private void descriptKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descriptKeyReleased
        if (!descript.getText().equals("")) {
            txtArea = true;
        } else {
            txtArea = false;
        }
        if (txtField == true && txtArea == true) {
            BtnOK.setEnabled(true);
        } else {
            BtnOK.setEnabled(false);
        }
    }//GEN-LAST:event_descriptKeyReleased

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        int row = DataTable.getSelectedRow();
        
        System.out.println("El valor de la fila es: " + row);
        
        if (row >= 0) {
            id = Integer.parseInt(DataTable.getValueAt(row, 0).toString());
            plataform.setText(DataTable.getValueAt(row, 1).toString());
            descript.setText(DataTable.getValueAt(row, 2).toString());
        } else {
            JOptionPane.showMessageDialog(null, "Sorry my friend!! :'( " + row);
        }
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement pst = cn.prepareStatement("UPDATE plataformas SET nombre = '" + plataform.getText() + "', descripcion = '" + descript.getText() + "' WHERE id = " + id);
            pst.executeUpdate();
            mostrarDatos();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        int row = DataTable.getSelectedRow();
        id = Integer.parseInt(DataTable.getValueAt(row, 0).toString());
        try{
            PreparedStatement pst = cn.prepareStatement("DELETE FROM plataformas WHERE id = " + id);
            pst.executeUpdate();
            mostrarDatos();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "sorry my friend :P");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void boxPlataformaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxPlataformaActionPerformed
        // TODO add your handling code here:
        int option = boxPlataforma.getSelectedIndex();
        //JOptionPane.showMessageDialog(null, "Seleccion " + option);
        
        String pt = (String) boxPlataforma.getSelectedItem();
        if (option > 0) {
            JOptionPane.showMessageDialog(null, "Elegistes " + pt);
        }
        
    }//GEN-LAST:event_boxPlataformaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Plataformas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Plataformas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Plataformas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Plataformas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Plataformas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnOK;
    private javax.swing.JTable DataTable;
    private javax.swing.JComboBox boxPlataforma;
    private javax.swing.JTextArea descript;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField plataform;
    // End of variables declaration//GEN-END:variables
}
