/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import conn.ConexionMySQL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class Poesia extends javax.swing.JFrame {

    ConexionMySQL cmsql = new ConexionMySQL();
    Connection cn = cmsql.conectBdd();
    
    /**
     * Creates new form Poesia
     */
    public Poesia() {
        initComponents();
        showDataP();
        showDataPa();
        ShowPoets();
    }
    
    public void ShowPoets() {
        poemaIdPoeta.removeAllItems();
        poemaIdPoeta.addItem("Selecciona un poeta: ");
        try {
            Statement stt = cn.createStatement();
            ResultSet rst = stt.executeQuery("Select * from poeta");
            
            while (rst.next()) {
                poemaIdPoeta.addItem(rst.getString(1) + "- " + rst.getString(2) + " " + rst.getString(3));
            }
        } catch (Exception ex) {
            System.out.println("Mensaje: " + ex.getMessage());
        }
    }
    
    public void showDataP() {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("ID Poeta");
        dtm.addColumn("Nombre");
        dtm.addColumn("Apellido Paterno");
        dtm.addColumn("Apellido Materno");
        dtm.addColumn("E-mail");
        dtm.addColumn("Pseudonimo");
        dtm.addColumn("Sexo");
        dtm.addColumn("Nacionalidad");
        
        DataTableP.setModel(dtm);
        
        try {
            String [] data = new String[8];
            Statement set = cn.createStatement();
            ResultSet rst = set.executeQuery("SELECT * FROM poeta");
            while(rst.next()) {
                data[0] = rst.getString(1);
                data[1] = rst.getString(2);
                data[2] = rst.getString(3);
                data[3] = rst.getString(4);
                data[4] = rst.getString(5);
                data[5] = rst.getString(6);
                data[6] = rst.getString(7);
                data[7] = rst.getString(8);
                dtm.addRow(data);
            }
            DataTableP.setModel(dtm);
        } catch (Exception ex) {
            System.out.println("Mensaje: \n" + ex.getMessage());
        }
    }
    
    public void showDataPa() {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("ID Poema");
        dtm.addColumn("Poeta");
        dtm.addColumn("Titulo");
        dtm.addColumn("Tipo");
        dtm.addColumn("Fecha");
        dtm.addColumn("Nacionalidad");
        
        DataTablePa.setModel(dtm);
        
        try {
            String [] data = new String[6];
            Statement set = cn.createStatement();
            ResultSet rst = set.executeQuery("SELECT * FROM poema");
            
            while(rst.next()) {
                
                Statement set2 = cn.createStatement();
                ResultSet rst2 = set2.executeQuery("SELECT nombre, aPaterno FROM poeta WHERE idPoeta = " + rst.getString(2));
                
                data[0] = rst.getString(1);
                while(rst2.next()) {
                    data[1] = rst2.getString(1) + " " + rst2.getString(2);
                }
                data[2] = rst.getString(3);
                data[3] = rst.getString(4);
                data[4] = rst.getString(5);
                data[5] = rst.getString(6);
                dtm.addRow(data);
            }
            DataTablePa.setModel(dtm);
        } catch (Exception ex) {
            System.out.println("Mensaje: \n" + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PopMenuP = new javax.swing.JPopupMenu();
        PopMenuPa = new javax.swing.JPopupMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pLname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pMlname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Pemail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pNickname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pSave = new javax.swing.JButton();
        pGen = new javax.swing.JComboBox();
        pNaci = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        poemTitulo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        poemFecha = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        poemaNacionalidad = new javax.swing.JComboBox();
        poemaIdPoeta = new javax.swing.JComboBox();
        poemaTipo = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DataTableP = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DataTablePa = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/home.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Inicio", jPanel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Insertar Poeta");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellido Paterno:");

        jLabel5.setText("Apellido Materno:");

        pMlname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pMlnameActionPerformed(evt);
            }
        });

        jLabel6.setText("E-mail:");

        jLabel7.setText("Pseudominio:");

        jLabel8.setText("Género:");

        jLabel9.setText("Nacionalidad:");

        pSave.setText("Guardar Poesía");
        pSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pSaveActionPerformed(evt);
            }
        });

        pGen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione uno:", "Femenino", "Masculino" }));

        pNaci.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione uno:", "Afghan (áfgan) - Afgano", "American (amérikan) - Americano", "Argentinian (ardchentínian) - Argentino", "Australian (ostréilian) - Australiano", "Austrian (óstrian) - Austríaco", "Belgian (béldchan) - Belga", "Bolivian (bolíivian) - Boliviano", "Brazilian (brasílian) - Brasileño", "British (brítish) - Británico", "Bulgarian (balguérian) - Búlgaro", "Canadian (kanéidian) - Canadiense", "Chilean (chílian) - Chileno", "Chinese (chainíis) - Chino", "Colombian (kolómbian) - Colombiano", "Costa Rican (kostaríikan) - Costarricense", "Cuban (kiúban) - Cubano", "Czech (chek) - Checo", "Danish (déinish) - Danés", "Dominican (domínikan) - Dominicano", "Dutch (dách) - Holandés", "Ecuadorean (ekuadórian) - Ecuadorean", "Egyptian (idchípshan) - Egipcio", "English (ínglish) - Inglés", "Filipino (filipínou) - Filipino", "Finnish (fínish) - Finlandés", "French (frénch) - Francés", "German (dchérman) - Alemán", "Greek (gríik) - Griego", "Greenlander (grinlánder) - Groenlandés", "Guatemalan (guatemálan) - Guatemalteco", "Haitian (héishan) - Haitiano", "Hawaiian (hauáian) - Hawaiano", "Honduran (hondúran) - Hondureño", "Hungarian (hanguérian) - Húngaro", "Icelandic (aislándik) - Islandés", "Indian (índian) - Indio", "Indonesian (indouníshan) - Indonesio", "Iranian (iránian) - Iraní", "Iraqui (iráki) - Iraqui", "Irish (áirish) - Irlandés", "Israeli (isréli) - Israelí", "Italian (itálian) - Italiano", "Jamaican (dchaméikan) - Jamaicano", "Japanese (dchapaníis) - Japonés", "korean (korían) - coreano", "Lebanese (lebaníis) - Libanés", "Malaysian (maléishan) - Malasio", "Maltese (moltíis) - Maltés", "Mexican (méksikan) - Mejicano", "Moroccan (morókan) - Marroquí", "Nepalese (nepalíis) - Nepalés", "New Zealander (niú síilander) - Neozelandés", "Nicaraguan (nikaráguan) - Nicaragüense", "Nigerian (naidchírian) - Nigeriano", "Norwegian (norwídchan) - Noruego", "Pakistani (pakistáni) - Paquistaní", "Palestinian (palestínian) - Palestino", "Panamanian (panaménian) - Panameño", "Paraguayan (paraguáian) - Paraguayo", "Peruvian (perúvian) - Peruano", "Polish (pólish) - Polaco", "Portuguese (porchuguíis) - Portugués", "Puerto Rican (puértou ríkan) - Puertorriqueño", "Rumanian (ruméinian) - Rumano", "Russian (ráshan) - Ruso", "Saudi Arabian (sáudi aréibian) - Saudita", "Scottish (skótish) - Escocés", "Singaporean (singaporéan) - Singaporean", "Spanish (spánish) - Español", "Swedish (suídish) - Sueco", "Swiss (suíis) - Suizo", "Syrian (sírian) - Sirio", "Tahitian (tahítian) - Tahitiano", "Thai (tái) - Tailandés", "Tunisian (tuníshan) - Tunecino", "Turkish (térkish) - Turco", "Ukrainian (iukréinian) - Ucraniano", "Uruguayan (iuruguáian) - Uruguayo", "Venezuelan (venesuélan) - Venezolano", "Vietnamese (vietnamíis) - Vietnamita", "Welsh (uélsh) - Galés", "Yugoslavian (iúgoslávian) - Yugoslavo" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pName)
                            .addComponent(pLname)
                            .addComponent(pMlname)
                            .addComponent(Pemail)
                            .addComponent(pNickname)
                            .addComponent(pGen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pNaci, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(372, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pSave)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pMlname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Pemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(pNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(pNaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                .addComponent(pSave)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Poeta", jPanel2);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Inserta Poema");

        jLabel11.setText("Poeta:");

        jLabel12.setText("Título:");

        jLabel13.setText("Tipo:");

        jLabel14.setText("Fecha:");

        jLabel15.setText("Nacionalidad:");

        jButton2.setText("Guardar Poeta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        poemaNacionalidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione uno:", "Afghan (áfgan) - Afgano", "American (amérikan) - Americano", "Argentinian (ardchentínian) - Argentino", "Australian (ostréilian) - Australiano", "Austrian (óstrian) - Austríaco", "Belgian (béldchan) - Belga", "Bolivian (bolíivian) - Boliviano", "Brazilian (brasílian) - Brasileño", "British (brítish) - Británico", "Bulgarian (balguérian) - Búlgaro", "Canadian (kanéidian) - Canadiense", "Chilean (chílian) - Chileno", "Chinese (chainíis) - Chino", "Colombian (kolómbian) - Colombiano", "Costa Rican (kostaríikan) - Costarricense", "Cuban (kiúban) - Cubano", "Czech (chek) - Checo", "Danish (déinish) - Danés", "Dominican (domínikan) - Dominicano", "Dutch (dách) - Holandés", "Ecuadorean (ekuadórian) - Ecuadorean", "Egyptian (idchípshan) - Egipcio", "English (ínglish) - Inglés", "Filipino (filipínou) - Filipino", "Finnish (fínish) - Finlandés", "French (frénch) - Francés", "German (dchérman) - Alemán", "Greek (gríik) - Griego", "Greenlander (grinlánder) - Groenlandés", "Guatemalan (guatemálan) - Guatemalteco", "Haitian (héishan) - Haitiano", "Hawaiian (hauáian) - Hawaiano", "Honduran (hondúran) - Hondureño", "Hungarian (hanguérian) - Húngaro", "Icelandic (aislándik) - Islandés", "Indian (índian) - Indio", "Indonesian (indouníshan) - Indonesio", "Iranian (iránian) - Iraní", "Iraqui (iráki) - Iraqui", "Irish (áirish) - Irlandés", "Israeli (isréli) - Israelí", "Italian (itálian) - Italiano", "Jamaican (dchaméikan) - Jamaicano", "Japanese (dchapaníis) - Japonés", "korean (korían) - coreano", "Lebanese (lebaníis) - Libanés", "Malaysian (maléishan) - Malasio", "Maltese (moltíis) - Maltés", "Mexican (méksikan) - Mejicano", "Moroccan (morókan) - Marroquí", "Nepalese (nepalíis) - Nepalés", "New Zealander (niú síilander) - Neozelandés", "Nicaraguan (nikaráguan) - Nicaragüense", "Nigerian (naidchírian) - Nigeriano", "Norwegian (norwídchan) - Noruego", "Pakistani (pakistáni) - Paquistaní", "Palestinian (palestínian) - Palestino", "Panamanian (panaménian) - Panameño", "Paraguayan (paraguáian) - Paraguayo", "Peruvian (perúvian) - Peruano", "Polish (pólish) - Polaco", "Portuguese (porchuguíis) - Portugués", "Puerto Rican (puértou ríkan) - Puertorriqueño", "Rumanian (ruméinian) - Rumano", "Russian (ráshan) - Ruso", "Saudi Arabian (sáudi aréibian) - Saudita", "Scottish (skótish) - Escocés", "Singaporean (singaporéan) - Singaporean", "Spanish (spánish) - Español", "Swedish (suídish) - Sueco", "Swiss (suíis) - Suizo", "Syrian (sírian) - Sirio", "Tahitian (tahítian) - Tahitiano", "Thai (tái) - Tailandés", "Tunisian (tuníshan) - Tunecino", "Turkish (térkish) - Turco", "Ukrainian (iukréinian) - Ucraniano", "Uruguayan (iuruguáian) - Uruguayo", "Venezuelan (venesuélan) - Venezolano", "Vietnamese (vietnamíis) - Vietnamita", "Welsh (uélsh) - Galés", "Yugoslavian (iúgoslávian) - Yugoslavo" }));

        poemaIdPoeta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione uno:", "1 - Gabriel Garcia Marquez", "2 - Maurice Scève", "3 - Pierre de Ronsard", "4 - Joachim du Bellay", "5 - Charles Baudelaire", "6 - Leconte de Lisle", "7 - Théodore de Banville", "8 - José María de Hérédia", "9 - Jules Laforgue", "10 - Jean Moréas", "11 - Stéphane Mallarmé", "12 - Paul Verlaine", "13 - Arthur Rimbaud", " " }));
        poemaIdPoeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poemaIdPoetaActionPerformed(evt);
            }
        });

        poemaTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleecione uno:", "Diabolico", "Analfabeto", "Intelectual", "Romantico", " " }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(poemaNacionalidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(poemFecha)
                            .addComponent(poemTitulo)
                            .addComponent(poemaIdPoeta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(poemaTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 330, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(304, 304, 304))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel10)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(poemaIdPoeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(poemTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(poemaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(poemFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(poemaNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 267, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Poema", jPanel3);

        DataTableP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        DataTableP.setComponentPopupMenu(PopMenuP);
        jScrollPane1.setViewportView(DataTableP);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Visualizar Poetas", jPanel4);

        DataTablePa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        DataTablePa.setComponentPopupMenu(PopMenuPa);
        jScrollPane2.setViewportView(DataTablePa);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Visualizar Poema", jPanel5);

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Insertar");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Modificar");
        jMenu1.add(jMenuItem2);

        jMenuItem5.setText("Visualizar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem3.setText("Eliminar");
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator1);

        jMenuItem4.setText("Salir");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void pMlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pMlnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pMlnameActionPerformed

    private void pSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pSaveActionPerformed

        try {
            PreparedStatement sent = cn.prepareStatement("INSERT INTO poeta (nombre, aPaterno, aMaterno, email, pseudonimo, sexo, nacionalidad) VALUES (?, ?, ?, ?, ?, ?, ?)");
            sent.setString(1, pName.getText());
            sent.setString(2, pLname.getText());
            sent.setString(3, pMlname.getText());
            sent.setString(4, Pemail.getText());
            sent.setString(5, pNickname.getText());
            sent.setString(6, pGen.getSelectedObjects().toString());
            sent.setString(7, pNaci.getSelectedObjects().toString());
            sent.executeUpdate();
            showDataP();
        } catch (Exception ex) {
            System.out.println("Sorry \n" + ex.getMessage());
        }

        clearFields();
        System.out.println("Exito!! :P");
        JOptionPane.showMessageDialog(null, "Exito!! :)");


        pSave.setEnabled(false);
    }//GEN-LAST:event_pSaveActionPerformed

    private void poemaIdPoetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poemaIdPoetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poemaIdPoetaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String idPoeta = (String) poemaIdPoeta.getSelectedItem();
        
        String[] parts = idPoeta.split("-");
        
        try {
            PreparedStatement sent = cn.prepareStatement("INSERT INTO poema (idPoeta, titulo, tipo, fecha, nacionalidad) VALUES (?, ?, ?, ?, ?)");
            sent.setString(1, parts[0]);
            sent.setString(2, poemTitulo.getText());
            sent.setString(3, (String) poemaTipo.getSelectedItem());
            sent.setString(4, poemFecha.getText());
            sent.setString(5, (String) poemaNacionalidad.getSelectedItem());
            sent.executeUpdate();
            showDataP();
        } catch (Exception ex) {
            System.out.println("Sorry \n" + ex.getMessage());
        }

        clearFields();
        System.out.println("Exito!! :P");
        JOptionPane.showMessageDialog(null, "Exito!! :)");
        
        showDataPa();

    }//GEN-LAST:event_jButton2ActionPerformed

    public void clearFields() {
        pName.setText("");
        pLname.setText("");
        pMlname.setText("");
        Pemail.setText("");
        pNickname.setText("");
        pGen.setSelectedIndex(0);
        pNaci.setSelectedIndex(0);
        poemFecha.setText("");
        poemTitulo.setText("");
        poemaTipo.setSelectedIndex(0);
        poemaIdPoeta.setSelectedIndex(0);
        poemaNacionalidad.setSelectedIndex(0);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Poesia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Poesia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Poesia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Poesia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Poesia().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DataTableP;
    private javax.swing.JTable DataTablePa;
    private javax.swing.JTextField Pemail;
    private javax.swing.JPopupMenu PopMenuP;
    private javax.swing.JPopupMenu PopMenuPa;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox pGen;
    private javax.swing.JTextField pLname;
    private javax.swing.JTextField pMlname;
    private javax.swing.JComboBox pNaci;
    private javax.swing.JTextField pName;
    private javax.swing.JTextField pNickname;
    private javax.swing.JButton pSave;
    private javax.swing.JTextField poemFecha;
    private javax.swing.JTextField poemTitulo;
    private javax.swing.JComboBox poemaIdPoeta;
    private javax.swing.JComboBox poemaNacionalidad;
    private javax.swing.JComboBox poemaTipo;
    // End of variables declaration//GEN-END:variables
}
