package hibernate.pojos;
// Generated 25-nov-2015 20:27:10 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ListOs generated by hbm2java
 */
@Entity
@Table(name = "ListOS", catalog = "movilNet"
)
public class ListOs implements java.io.Serializable {

    private Integer idListOs;
    private String osName;

    public ListOs() {
    }

    public ListOs(Integer idListOs) {
        this.idListOs = idListOs;
    }

    public ListOs(String osName) {
        this.osName = osName;
    }

    public ListOs(Integer idListOs, String osName) {
        this.idListOs = idListOs;
        this.osName = osName;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idListOS", unique = true, nullable = false)
    public Integer getIdListOs() {
        return this.idListOs;
    }

    public void setIdListOs(Integer idListOs) {
        this.idListOs = idListOs;
    }

    @Column(name = "osName", nullable = false, length = 45)
    public String getOsName() {
        return this.osName;
    }

    public void setOsName(String osName) {
        this.osName = osName;
    }

}
