package hibernate.pojos;
// Generated 25-nov-2015 20:27:10 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ListTrademark generated by hbm2java
 */
@Entity
@Table(name = "ListTrademark", catalog = "movilNet"
)
public class ListTrademark implements java.io.Serializable {

    private Integer idListTrademark;
    private String trademarkName;
    private String trademarkDesc;
    private byte[] trademarkLogo;

    public ListTrademark() {
    }

    public ListTrademark(Integer idListTrademark) {
        this.idListTrademark = idListTrademark;
    }

    public ListTrademark(String trademarkName, String trademarkDesc, byte[] trademarkLogo) {
        this.trademarkName = trademarkName;
        this.trademarkDesc = trademarkDesc;
        this.trademarkLogo = trademarkLogo;
    }

    public ListTrademark(Integer idListTrademark, String trademarkName, String trademarkDesc, byte[] trademarkLogo) {
        this.idListTrademark = idListTrademark;
        this.trademarkName = trademarkName;
        this.trademarkDesc = trademarkDesc;
        this.trademarkLogo = trademarkLogo;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idListTrademark", unique = true, nullable = false)
    public Integer getIdListTrademark() {
        return this.idListTrademark;
    }

    public void setIdListTrademark(Integer idListTrademark) {
        this.idListTrademark = idListTrademark;
    }

    @Column(name = "trademarkName", nullable = false, length = 45)
    public String getTrademarkName() {
        return this.trademarkName;
    }

    public void setTrademarkName(String trademarkName) {
        this.trademarkName = trademarkName;
    }

    @Column(name = "trademarkDesc", length = 45)
    public String getTrademarkDesc() {
        return this.trademarkDesc;
    }

    public void setTrademarkDesc(String trademarkDesc) {
        this.trademarkDesc = trademarkDesc;
    }

    @Column(name = "trademarkLogo")
    public byte[] getTrademarkLogo() {
        return this.trademarkLogo;
    }

    public void setTrademarkLogo(byte[] trademarkLogo) {
        this.trademarkLogo = trademarkLogo;
    }

}
