package hibernate.pojos;
// Generated 25-nov-2015 20:27:10 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ListModel generated by hbm2java
 */
@Entity
@Table(name = "ListModel", catalog = "movilNet"
)
public class ListModel implements java.io.Serializable {

    private Integer idListModel;
    private int idListTrademark;
    private String modelName;
    private String modelDesc;
    private Date modelReleaseDate;
    private byte[] modelPhone;

    public ListModel() {
    }

    public ListModel(Integer idListModel) {
        this.idListModel = idListModel;
    }

    public ListModel(int idListTrademark, String modelName, String modelDesc, Date modelReleaseDate, byte[] modelPhone) {
        this.idListTrademark = idListTrademark;
        this.modelName = modelName;
        this.modelDesc = modelDesc;
        this.modelReleaseDate = modelReleaseDate;
        this.modelPhone = modelPhone;
    }

    public ListModel(Integer idListModel, int idListTrademark, String modelName, String modelDesc, Date modelReleaseDate, byte[] modelPhone) {
        this.idListModel = idListModel;
        this.idListTrademark = idListTrademark;
        this.modelName = modelName;
        this.modelDesc = modelDesc;
        this.modelReleaseDate = modelReleaseDate;
        this.modelPhone = modelPhone;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idListModel", unique = true, nullable = false)
    public Integer getIdListModel() {
        return this.idListModel;
    }

    public void setIdListModel(Integer idListModel) {
        this.idListModel = idListModel;
    }

    @Column(name = "idListTrademark", nullable = false)
    public int getIdListTrademark() {
        return this.idListTrademark;
    }

    public void setIdListTrademark(int idListTrademark) {
        this.idListTrademark = idListTrademark;
    }

    @Column(name = "modelName", nullable = false, length = 45)
    public String getModelName() {
        return this.modelName;
    }

    public void setModelName(String modelName) {
        this.modelName = modelName;
    }

    @Column(name = "modelDesc", length = 45)
    public String getModelDesc() {
        return this.modelDesc;
    }

    public void setModelDesc(String modelDesc) {
        this.modelDesc = modelDesc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "modelReleaseDate", length = 10)
    public Date getModelReleaseDate() {
        return this.modelReleaseDate;
    }

    public void setModelReleaseDate(Date modelReleaseDate) {
        this.modelReleaseDate = modelReleaseDate;
    }

    @Column(name = "modelPhone")
    public byte[] getModelPhone() {
        return this.modelPhone;
    }

    public void setModelPhone(byte[] modelPhone) {
        this.modelPhone = modelPhone;
    }

}
