package hibernate.pojos;
// Generated 25-nov-2015 20:27:10 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Login generated by hbm2java
 */
@Entity
@Table(name = "Login", catalog = "movilNet"
)
public class Login implements java.io.Serializable {

    private Integer idLogin;
    private int idUsers;
    private String loginName;
    private String loginPassword;

    public Login() {
    }

    public Login(Integer idLogin) {
        this.idLogin = idLogin;
    }

    public Login(String loginName, String loginPassword) {
        this.loginName = loginName;
        this.loginPassword = loginPassword;
    }

    public Login(int idUsers, String loginName, String loginPassword) {
        this.idUsers = idUsers;
        this.loginName = loginName;
        this.loginPassword = loginPassword;
    }

    public Login(Integer idLogin, int idUsers, String loginName, String loginPassword) {
        this.idLogin = idLogin;
        this.idUsers = idUsers;
        this.loginName = loginName;
        this.loginPassword = loginPassword;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idLogin", unique = true, nullable = false)
    public Integer getIdLogin() {
        return this.idLogin;
    }

    public void setIdLogin(Integer idLogin) {
        this.idLogin = idLogin;
    }

    @Column(name = "idUsers", nullable = false)
    public int getIdUsers() {
        return this.idUsers;
    }

    public void setIdUsers(int idUsers) {
        this.idUsers = idUsers;
    }

    @Column(name = "loginName", nullable = false, length = 45)
    public String getLoginName() {
        return this.loginName;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    @Column(name = "loginPassword", nullable = false, length = 45)
    public String getLoginPassword() {
        return this.loginPassword;
    }

    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword;
    }

}
