package hibernate.pojos;
// Generated 25-nov-2015 20:27:10 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OrderPhone generated by hbm2java
 */
@Entity
@Table(name = "OrderPhone", catalog = "movilNet"
)
public class OrderPhone implements java.io.Serializable {

    private Integer idOrderPhone;
    private Integer idPhone;
    private Integer idOrder;
    private int orderQuantity;
    private String orderUnitPrice;
    private String orderTotalPhone;

    public OrderPhone() {
    }

    public OrderPhone(Integer idOrderPhone) {
        this.idOrderPhone = idOrderPhone;
    }

    public OrderPhone(Integer idPhone, Integer idOrder, int orderQuantity, String orderUnitPrice, String orderTotalPhone) {
        this.idPhone = idPhone;
        this.idOrder = idOrder;
        this.orderQuantity = orderQuantity;
        this.orderUnitPrice = orderUnitPrice;
        this.orderTotalPhone = orderTotalPhone;
    }

    public OrderPhone(Integer idOrderPhone, Integer idPhone, Integer idOrder, int orderQuantity, String orderUnitPrice, String orderTotalPhone) {
        this.idOrderPhone = idOrderPhone;
        this.idPhone = idPhone;
        this.idOrder = idOrder;
        this.orderQuantity = orderQuantity;
        this.orderUnitPrice = orderUnitPrice;
        this.orderTotalPhone = orderTotalPhone;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idOrderPhone", unique = true, nullable = false)
    public Integer getIdOrderPhone() {
        return this.idOrderPhone;
    }

    public void setIdOrderPhone(Integer idOrderPhone) {
        this.idOrderPhone = idOrderPhone;
    }

    @Column(name = "idPhone")
    public Integer getIdPhone() {
        return this.idPhone;
    }

    public void setIdPhone(Integer idPhone) {
        this.idPhone = idPhone;
    }

    @Column(name = "idOrder")
    public Integer getIdOrder() {
        return this.idOrder;
    }

    public void setIdOrder(Integer idOrder) {
        this.idOrder = idOrder;
    }

    @Column(name = "orderQuantity", nullable = false)
    public int getOrderQuantity() {
        return this.orderQuantity;
    }

    public void setOrderQuantity(int orderQuantity) {
        this.orderQuantity = orderQuantity;
    }

    @Column(name = "orderUnitPrice", nullable = false, length = 16777215)
    public String getOrderUnitPrice() {
        return this.orderUnitPrice;
    }

    public void setOrderUnitPrice(String orderUnitPrice) {
        this.orderUnitPrice = orderUnitPrice;
    }

    @Column(name = "orderTotalPhone", nullable = false, length = 16777215)
    public String getOrderTotalPhone() {
        return this.orderTotalPhone;
    }

    public void setOrderTotalPhone(String orderTotalPhone) {
        this.orderTotalPhone = orderTotalPhone;
    }

}
