package hibernate.pojos;
// Generated 25-nov-2015 20:27:10 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "Order", catalog = "movilNet"
)
public class Order implements java.io.Serializable {

    private Integer idOrder;
    private int idAddress;
    private Date datePurchase;
    private String totalAmount;

    public Order() {
    }

    public Order(Integer idOrder) {
        this.idOrder = idOrder;
    }

    public Order(int idAddress, Date datePurchase, String totalAmount) {
        this.idAddress = idAddress;
        this.datePurchase = datePurchase;
        this.totalAmount = totalAmount;
    }

    public Order(Integer idOrder, int idAddress, Date datePurchase, String totalAmount) {
        this.idOrder = idOrder;
        this.idAddress = idAddress;
        this.datePurchase = datePurchase;
        this.totalAmount = totalAmount;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idOrder", unique = true, nullable = false)
    public Integer getIdOrder() {
        return this.idOrder;
    }

    public void setIdOrder(Integer idOrder) {
        this.idOrder = idOrder;
    }

    @Column(name = "idAddress", nullable = false)
    public int getIdAddress() {
        return this.idAddress;
    }

    public void setIdAddress(int idAddress) {
        this.idAddress = idAddress;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "datePurchase", nullable = false, length = 19)
    public Date getDatePurchase() {
        return this.datePurchase;
    }

    public void setDatePurchase(Date datePurchase) {
        this.datePurchase = datePurchase;
    }

    @Column(name = "totalAmount", nullable = false, length = 16777215)
    public String getTotalAmount() {
        return this.totalAmount;
    }

    public void setTotalAmount(String totalAmount) {
        this.totalAmount = totalAmount;
    }

}
