package hibernate.pojos;
// Generated 25-nov-2015 20:27:10 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserType generated by hbm2java
 */
@Entity
@Table(name = "UserType", catalog = "movilNet"
)
public class UserType implements java.io.Serializable {

    private Integer idUserType;
    private String descType;

    public UserType() {
    }

    public UserType(Integer idUserType) {
        this.idUserType = idUserType;
    }

    public UserType(String descType) {
        this.descType = descType;
    }

    public UserType(Integer idUserType, String descType) {
        this.idUserType = idUserType;
        this.descType = descType;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idUserType", unique = true, nullable = false)
    public Integer getIdUserType() {
        return this.idUserType;
    }

    public void setIdUserType(Integer idUserType) {
        this.idUserType = idUserType;
    }

    @Column(name = "descType", nullable = false, length = 45)
    public String getDescType() {
        return this.descType;
    }

    public void setDescType(String descType) {
        this.descType = descType;
    }

}
