/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dsescuela;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import conn.ConexionMySQL;
import java.sql.*;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author XxYoshiBlackxX
 */
public class DSEscuela extends javax.swing.JFrame {

    ConexionMySQL cmsql = new ConexionMySQL();
    Connection cn = cmsql.conectBdd();
    boolean[] fields = new boolean[10];
    int id = 0;

    /**
     * Creates new form DSEscuela
     */
    public DSEscuela() {
        initComponents();
        showData();
    }

    public void showData() {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("ID");
        dtm.addColumn("Matricula");
        dtm.addColumn("Grupo");
        dtm.addColumn("Nombre");
        dtm.addColumn("Apellido P");
        dtm.addColumn("Apellido M");
        dtm.addColumn("Dirección");
        dtm.addColumn("Teléfono");
        dtm.addColumn("E-mail");
        dtm.addColumn("Nacimiento");
        dtm.addColumn("Sexo");
        dtm.addColumn("Registro");

        DataTable.setModel(dtm);

        try {
            String[] data = new String[12];
            Statement set = cn.createStatement();
            ResultSet rst = set.executeQuery("SELECT * FROM students");
            while (rst.next()) {
                data[0] = rst.getString(1);
                data[1] = rst.getString(2);
                data[2] = rst.getString(3);
                data[3] = rst.getString(4);
                data[4] = rst.getString(5);
                data[5] = rst.getString(6);
                data[6] = rst.getString(7);
                data[7] = rst.getString(8);
                data[8] = rst.getString(9);
                data[9] = rst.getString(10);
                data[10] = rst.getString(11);
                data[11] = rst.getString(12);
                dtm.addRow(data);
            }
            DataTable.setModel(dtm);
        } catch (Exception ex) {
            System.out.println("Mensaje: \n" + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Actualizar = new javax.swing.JMenuItem();
        Eliminar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        matricula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        grupo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        papellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mapellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dir = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        update = new javax.swing.JButton();
        genero = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jCalendarButton1 = new net.sourceforge.jcalendarbutton.JCalendarButton();
        nacimiento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        DataTable = new javax.swing.JTable();

        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Actualizar);

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Eliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Control de alumnos");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Control de alumnos"));

        jLabel1.setText("Matricula:");

        matricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                matriculaKeyReleased(evt);
            }
        });

        jLabel2.setText("Grupo:");

        grupo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                grupoKeyReleased(evt);
            }
        });

        jLabel3.setText("Nombre(s):");

        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombreKeyReleased(evt);
            }
        });

        jLabel4.setText("Apellido Paterno:");

        papellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                papellidoKeyPressed(evt);
            }
        });

        jLabel5.setText("Apellido Materno:");

        mapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mapellidoKeyReleased(evt);
            }
        });

        jLabel6.setText("Dirección:");

        dir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dirKeyReleased(evt);
            }
        });

        jLabel7.setText("Teléfono:");

        tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                telKeyReleased(evt);
            }
        });

        jLabel8.setText("Correo Electrónico:");

        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailKeyReleased(evt);
            }
        });

        jLabel9.setText("Fecha de Nacimiento:");

        jLabel10.setText("Genero:");

        save.setText("Guardar");
        save.setEnabled(false);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        update.setText("Modificar");
        update.setEnabled(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        genero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione uno:", "Femenino", "Masculino" }));
        genero.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                generoItemStateChanged(evt);
            }
        });

        jCalendarButton1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCalendarButton1PropertyChange(evt);
            }
        });

        nacimiento.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(save)
                        .addGap(53, 53, 53)
                        .addComponent(update))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(nombre))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel4))
                                            .addGap(1, 1, 1))
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(genero, 0, 500, Short.MAX_VALUE)
                                    .addComponent(papellido)
                                    .addComponent(mapellido)
                                    .addComponent(dir)
                                    .addComponent(tel)
                                    .addComponent(email, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(grupo)
                                    .addComponent(nacimiento)
                                    .addComponent(matricula, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCalendarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(papellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(mapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCalendarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(update)))
        );

        DataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        DataTable.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(DataTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Control de Alumnos");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateOnlyPopupChanged(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateOnlyPopupChanged
        if (evt.getNewValue() instanceof Date) {
            setDate((Date) evt.getNewValue());
        }
    }//GEN-LAST:event_dateOnlyPopupChanged

    private void jCalendarButton1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCalendarButton1PropertyChange
        if (evt.getNewValue() instanceof Date) {
            setDate((Date) evt.getNewValue());
        }
    }//GEN-LAST:event_jCalendarButton1PropertyChange

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        try {
            PreparedStatement sent = cn.prepareStatement("INSERT INTO students (regtag, groupa, name, last_name, ml_name, address, Hphone, email, birthdate, sex) "
                    + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
            sent.setString(1, matricula.getText());
            sent.setString(2, grupo.getText());
            sent.setString(3, nombre.getText());
            sent.setString(4, papellido.getText());
            sent.setString(5, mapellido.getText());
            sent.setString(6, dir.getText());
            sent.setString(7, tel.getText());
            sent.setString(8, email.getText());
            sent.setString(9, nacimiento.getText());
            sent.setString(10, genero.getSelectedItem().toString());
            sent.executeUpdate();
            showData();
        } catch (Exception ex) {
            System.out.println("Sorry \n" + ex.getMessage());
        }

        clearFields();
        JOptionPane.showMessageDialog(null, "Exito!! :)");
    }//GEN-LAST:event_saveActionPerformed

    private void matriculaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matriculaKeyReleased
        if (!matricula.getText().equals("")) {
            fields[0] = true;
        } else {
            fields[0] = false;
        }
        checkFields();
    }//GEN-LAST:event_matriculaKeyReleased

    private void grupoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_grupoKeyReleased
        if (!grupo.getText().equals("")) {
            fields[1] = true;
        } else {
            fields[1] = false;
        }
        checkFields();
    }//GEN-LAST:event_grupoKeyReleased

    private void nombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyReleased
        if (!nombre.getText().equals("")) {
            fields[2] = true;
        } else {
            fields[2] = false;
        }
        checkFields();
    }//GEN-LAST:event_nombreKeyReleased

    private void papellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_papellidoKeyPressed
        if (!papellido.getText().equals("")) {
            fields[3] = true;
        } else {
            fields[3] = false;
        }
        checkFields();
    }//GEN-LAST:event_papellidoKeyPressed

    private void mapellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mapellidoKeyReleased
        if (!mapellido.getText().equals("")) {
            fields[4] = true;
        } else {
            fields[4] = false;
        }
        checkFields();
    }//GEN-LAST:event_mapellidoKeyReleased

    private void dirKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dirKeyReleased
        if (!dir.getText().equals("")) {
            fields[5] = true;
        } else {
            fields[5] = false;
        }
        checkFields();
    }//GEN-LAST:event_dirKeyReleased

    private void telKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telKeyReleased
        if (!tel.getText().equals("")) {
            fields[6] = true;
        } else {
            fields[6] = false;
        }
        checkFields();
    }//GEN-LAST:event_telKeyReleased

    private void emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyReleased
        if (!email.getText().equals("")) {
            fields[7] = true;
        } else {
            fields[7] = false;
        }
        checkFields();
    }//GEN-LAST:event_emailKeyReleased

    private void generoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_generoItemStateChanged
        if (genero.getSelectedIndex() != 0) {
            fields[8] = true;
        } else {
            fields[8] = false;
        }
        checkFields();
    }//GEN-LAST:event_generoItemStateChanged

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try {
            String data = "regtag = '" + matricula.getText() + "', groupa = '" + grupo.getText() + "', name = '" + nombre.getText() + "', last_name = '" + papellido.getText() + "', ml_name = '" + mapellido.getText() + "', address = '" + dir.getText() + "', "
                    + "Hphone = " + tel.getText() + ", email = '" + email.getText() + "', birthdate = '" + nacimiento.getText() + "', sex = '" + genero.getSelectedItem().toString() + "'";
            PreparedStatement pst = cn.prepareStatement("UPDATE students SET " + data + " WHERE id_student = " + id);
            pst.executeUpdate();
            showData();
            //update.setEnabled(false);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_updateActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        int row = DataTable.getSelectedRow();
        
        System.out.println("El valor de la fila es: " + row);
        
        if (row >= 0) {
            id = Integer.parseInt(DataTable.getValueAt(row, 0).toString());
            matricula.setText(DataTable.getValueAt(row, 1).toString());
            grupo.setText(DataTable.getValueAt(row, 2).toString());
            nombre.setText(DataTable.getValueAt(row, 3).toString());
            papellido.setText(DataTable.getValueAt(row, 4).toString());
            mapellido.setText(DataTable.getValueAt(row, 5).toString());
            dir.setText(DataTable.getValueAt(row, 6).toString());
            tel.setText(DataTable.getValueAt(row, 7).toString());
            email.setText(DataTable.getValueAt(row, 8).toString());
            nacimiento.setText(DataTable.getValueAt(row, 9).toString());
            String gene = DataTable.getValueAt(row, 10).toString();
            if (gene.endsWith("Femenino")) {
                genero.setSelectedIndex(1);
            } else if (gene.endsWith("Masculino")) {
                genero.setSelectedIndex(2);
            } else
                genero.setSelectedIndex(0);
            update.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "Sorry my friend!! :'( " + row);
        }
    }//GEN-LAST:event_ActualizarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        int row = DataTable.getSelectedRow();
        id = Integer.parseInt(DataTable.getValueAt(row, 0).toString());
        try{
            PreparedStatement pst = cn.prepareStatement("DELETE FROM students WHERE id_student = " + id);
            pst.executeUpdate();
            showData();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "sorry my friend :P");
        }
    }//GEN-LAST:event_EliminarActionPerformed

    public void setDate(String dateString) {
        Date date = null;
        try {
            if ((dateString != null) && (dateString.length() > 0)) {
                date = dateFormat.parse(dateString);
            }
        } catch (Exception e) {
            date = null;
        }
        this.setDate(date);
    }

    public void setDate(Date date) {
        String dateString = "";
        if (date != null) {
            dateString = new SimpleDateFormat("yyyy-MM-dd").format(date);
        }
        nacimiento.setText(dateString);
        jCalendarButton1.setTargetDate(date);
        fields[9] = true;

        checkFields();
    }

    public void checkFields() {
        int cnt = 0;
        for (int x = 0; x < fields.length; x++) {
            //System.out.println("Campo " + x + ": " + fields[x]);
            if (fields[x] == true) {
                cnt++;
            }
        }
        //System.out.println(cnt);

        if (cnt == 10) {
            save.setEnabled(true);
        } else {
            save.setEnabled(false);
        }
    }
    
    public void clearFields() {
        matricula.setText("");
        grupo.setText("");
        nombre.setText("");
        papellido.setText("");
        mapellido.setText("");
        dir.setText("");
        tel.setText("");
        email.setText("");
        genero.setSelectedIndex(0);
        nacimiento.setText("");
        Arrays.fill(fields, false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DSEscuela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DSEscuela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DSEscuela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DSEscuela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DSEscuela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Actualizar;
    private javax.swing.JTable DataTable;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JTextField dir;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox genero;
    private javax.swing.JTextField grupo;
    private net.sourceforge.jcalendarbutton.JCalendarButton jCalendarButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mapellido;
    private javax.swing.JTextField matricula;
    private javax.swing.JTextField nacimiento;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField papellido;
    private javax.swing.JButton save;
    private javax.swing.JTextField tel;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    public static DateFormat dateFormat = DateFormat.getDateInstance(DateFormat.MEDIUM);

}
