package test;

import javax.swing.JOptionPane;
import modelo.dao.PruebaDAO;
import modelo.dto.PruebaDTO;

public class GUIPrueba extends javax.swing.JFrame {

    /** Creates new form GUIPrueba */
    public GUIPrueba() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("EMAIL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 30, 60, 40);

        jLabel2.setText("NOMBRE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 60, 60, 40);

        jLabel3.setText("EDAD");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 90, 60, 40);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(140, 40, 100, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(140, 70, 100, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(140, 100, 100, 20);

        jButton1.setText("NUEVO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 40, 67, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PruebaDTO dto = new PruebaDTO();
        dto.setEmail(jTextField1.getText());
        dto.setNombre(jTextField2.getText());
        dto.setEdad(Integer.parseInt(jTextField3.getText()));
        PruebaDAO dao = new PruebaDAO();
//        System.out.println(dao.create(dto));
        JOptionPane.showMessageDialog(null, dao.create(dto));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

}
