/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ArticuloFrame.java
 *
 * Created on 16/12/2009, 12:45:28 PM
 */
package view;

import modelo.dto.ArticuloDTO;
import modelo.facade.ServicioInventario;
/**
 *
 * @author Administrador
 */
public class ArticuloFrame extends javax.swing.JFrame {
    /** Creates new form ArticuloFrame */
    public ArticuloFrame() {
        initComponents();
    }
    ArticuloDTO articuloDTO;
    ServicioInventario servicioInventario;
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("New");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 180, 110, 23);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(190, 50, 130, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(190, 80, 130, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(190, 110, 130, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(190, 140, 130, 20);

        jLabel1.setText("Clave del articulo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 50, 100, 14);

        jLabel2.setText("Descripción");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 80, 100, 14);

        jLabel3.setText("Precio");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 110, 100, 14);

        jLabel4.setText("Existencia");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 140, 100, 14);

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 210, 110, 23);

        jButton3.setText("Read");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 240, 110, 23);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-408)/2, (screenSize.height-334)/2, 408, 334);
    }// </editor-fold>//GEN-END:initComponents
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        articuloDTO = new ArticuloDTO();
        articuloDTO.setClaveArt(jTextField1.getText());
        articuloDTO.setDescripcion(jTextField2.getText());
        articuloDTO.setPrecio(Double.parseDouble(jTextField3.getText()));
        articuloDTO.setExistencia(Integer.parseInt(jTextField4.getText()));

        servicioInventario = new ServicioInventario();

        try {
            servicioInventario.crearArticulo(articuloDTO);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        articuloDTO = new ArticuloDTO();
        articuloDTO.setClaveArt(jTextField1.getText());
        servicioInventario = new ServicioInventario();

        try {
            servicioInventario.borrarArticulo(articuloDTO);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        articuloDTO = new ArticuloDTO();
        articuloDTO.setClaveArt(jTextField1.getText());
        servicioInventario = new ServicioInventario();

        try {
            articuloDTO = servicioInventario.consultaArticulo(articuloDTO);
            jTextField1.setText(articuloDTO.getClaveArt());
            jTextField2.setText(articuloDTO.getDescripcion());
            jTextField3.setText("" + articuloDTO.getPrecio());
            jTextField4.setText("" + articuloDTO.getExistencia());
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ArticuloFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
