package Pojo;
// Generated 03-jul-2014 0:52:05 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Tproducto generated by hbm2java
 */
public class Tproducto  implements java.io.Serializable {


     private Integer idProducto;
     private String codigoBarras;
     private String nombre;
     private BigDecimal precioVentaUnitario;
     private int cantidad;
     private Set tventadetalles = new HashSet(0);

    public Tproducto() {
    }

	
    public Tproducto(String codigoBarras, String nombre, BigDecimal precioVentaUnitario, int cantidad) {
        this.codigoBarras = codigoBarras;
        this.nombre = nombre;
        this.precioVentaUnitario = precioVentaUnitario;
        this.cantidad = cantidad;
    }
    public Tproducto(String codigoBarras, String nombre, BigDecimal precioVentaUnitario, int cantidad, Set tventadetalles) {
       this.codigoBarras = codigoBarras;
       this.nombre = nombre;
       this.precioVentaUnitario = precioVentaUnitario;
       this.cantidad = cantidad;
       this.tventadetalles = tventadetalles;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public String getCodigoBarras() {
        return this.codigoBarras;
    }
    
    public void setCodigoBarras(String codigoBarras) {
        this.codigoBarras = codigoBarras;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getPrecioVentaUnitario() {
        return this.precioVentaUnitario;
    }
    
    public void setPrecioVentaUnitario(BigDecimal precioVentaUnitario) {
        this.precioVentaUnitario = precioVentaUnitario;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public Set getTventadetalles() {
        return this.tventadetalles;
    }
    
    public void setTventadetalles(Set tventadetalles) {
        this.tventadetalles = tventadetalles;
    }




}


